server:
  port: 8082

spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://localhost:3306/user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20                   # 最大连接数

  application:
    name: user-center
  cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
#          namespace: 4a62abd7-e86d-447f-9dbb-5c844988d996
          cluster-name: NJ
          metadata:
            version: v1


management:
  endpoints:
    web:
      exposure:
        include: '*'
