server:
  port: 8082


spring:
  application:
    name: user-center

  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://localhost:3306/user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20                   # 最大连接数


  cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
#          namespace: 4a62abd7-e86d-447f-9dbb-5c844988d996
          cluster-name: NJ
          metadata:
            version: v1

  kafka:
    bootstrap-servers: zengshen.org:9092
    producer:
      retries: 3
    consumer:
      auto-offset-reset: latest
  zipkin:
    sender:
      type: kafka # 默认是 web
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      #ProbabilityBasedSampler 抽样策略
      probability: 0.1  # 采样比例, 1.0 表示 100%, 默认是 0.1
      # RateLimitingSampler 抽样策略, 设置了限速采集, spring.sleuth.sampler.probability 属性值无效
      rate: 1  # 每秒间隔接受的 trace 量

management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpth:mapping/*.xml
