server:
  port: 8840

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      # 让gateway通过服务发现组件找到其他的服务
      routes:
        - id: after_route
          uri: lb://user-center
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            # 自定义TimeBetween谓词规则
            - TimeBetween=上午9:00,下午10:00
          filters:
            # 请求添加header, key, value
            - AddRequestHeader=X-Request-Zeng, Shen
            - PreLog=a,b
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always