server:
  port: 8000
spring:
  application:
    name: spring-boot-admin-server
  security:
    user:
      name: zengshen
      password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          management:
            contenxt-path: /actuator
          user.name: zengshen
          user.passsword: 123456


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
  endpoint:
    health:
      show-details: always





