server:
  port: 8000
spring:
  application:
    name: spring-boot-admin

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

